import { Employee } from './employee'
export const Employees: Employee[] = [
    { id:1, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:2, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:3, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:4, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:5, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:6, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:7, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:8, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:9, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:10, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:11, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:12, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:13, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:14, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:15, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:16, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:17, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:18, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:19, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:20, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:21, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:22, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:23, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:24, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:25, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:26, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:27, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:28, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:29, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:30, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:31, firstName: 'Julius', lastName: 'Bacosa', address: 'test'},
    { id:32, firstName: 'Julius', lastName: 'Bacosa', address: 'test'}
];